version: '3.9'

services:
  backend:
    image: document-backend:0.1
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:6
    container_name: document_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
