version: '3.9'

services:
  backend:
    image: document-backend:0.8
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/document-generator
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_TEMPLATES_BUCKET_NAME=templates
    depends_on:
      - mongo
      - minio
    volumes:
      - ./backend/.:/app
    restart: always

  mongo:
    image: mongo:6
    container_name: document_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: always

  minio:
    image: minio/minio
    container_name: document_minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Konsola MinIO
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
  

