version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Wymuszenie budowania bez cache
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app

