version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  fileserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/files:/usr/share/nginx/html/files:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
